//
//  File.swift
//  
//
//  Created by Gennaro Frazzingaro on 6/25/21.
//

import Foundation

// KV Schema

let kKBTypedKeyValuePairsDbSchema = """
CREATE TABLE IF NOT EXISTS "link" (
id TEXT PRIMARY KEY NOT NULL,
subject TEXT NOT NULL,
predicate TEXT NOT NULL,
object TEXT NOT NULL,
count INTEGER DEFAULT 1,
attributes TEXT
);
CREATE TABLE IF NOT EXISTS "intval"(
k TEXT PRIMARY KEY NOT NULL,
v INTEGER,
t TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "realval"(
k TEXT PRIMARY KEY NOT NULL,
v REAL,
t TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "textval"(
k TEXT PRIMARY KEY NOT NULL,
v TEXT,
t TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "blobval"(
k TEXT PRIMARY KEY NOT NULL,
v BLOB,
t TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
PRAGMA case_sensitive_like = true
"""
